import { promises as fs } from "node:fs";
import { Bundle } from "../okf/bundle.js";

/** One tool invocation in an agent run. */
export interface TraceStep {
  seq: number;
  tool: string;
  /** Human-readable argument (query text, concept path…). */
  summary: string;
  /** Concept paths touched/returned by this step. */
  paths: string[];
  /** True for write tools. */
  write?: boolean;
}

export interface QueryTrace {
  id: string;
  kind: "query" | "mutation" | "chat";
  /** The user input that started the run (truncated). */
  input: string;
  startedAt: string;
  durationMs: number;
  steps: TraceStep[];
  /** Final answer/summary (truncated). */
  answer: string;
  /** Compact one-line notation of the traversal. */
  notation: string;
}

/** Collects steps during one agent run. Thread one instance through the tools. */
export class TraceRecorder {
  readonly steps: TraceStep[] = [];
  private readonly t0 = Date.now();

  record(tool: string, summary: string, paths: string[], write = false): void {
    this.steps.push({ seq: this.steps.length + 1, tool, summary, paths, write });
  }

  finalize(kind: QueryTrace["kind"], input: string, answer: string): QueryTrace {
    return {
      id: `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`,
      kind,
      input: truncate(input, 300),
      startedAt: new Date(this.t0).toISOString(),
      durationMs: Date.now() - this.t0,
      steps: this.steps,
      answer: truncate(answer, 500),
      notation: buildNotation(this.steps),
    };
  }
}

/** Compact single-line traversal notation, e.g.
 *  `search "rate limit" (2) → read /apis/billing-api.md → ✓` */
export function buildNotation(steps: TraceStep[]): string {
  const parts = steps.map((s) => {
    switch (s.tool) {
      case "search_knowledge":
        return `search "${truncate(s.summary, 30)}" (${s.paths.length})`;
      case "read_concept":
        return `read ${shortPath(s.paths[0] ?? s.summary)}`;
      case "list_directory":
        return "browse layout";
      case "lint_knowledge":
        return "lint graph";
      case "write_concept":
        return `write ${shortPath(s.paths[0] ?? "")}`;
      case "patch_concept":
        return `patch ${shortPath(s.paths[0] ?? "")}`;
      case "delete_concept":
        return `delete ${shortPath(s.paths[0] ?? "")}`;
      default:
        return s.tool;
    }
  });
  return [...parts, "✓"].join(" → ");
}

function shortPath(p: string): string {
  return p.split("/").pop() ?? p;
}

function truncate(s: string, n: number): string {
  return s.length > n ? s.slice(0, n - 1) + "…" : s;
}

const MAX_TRACES = 50;

/**
 * Persists traces as JSON under <bundleRoot>/.traces/ — a dot-directory the
 * OKF walkers ignore, so traces never touch conformance or the graph.
 */
export class TraceStore {
  private readonly bundle: Bundle;
  private readonly dir = "/.traces";

  constructor(bundleRoot: string) {
    this.bundle = new Bundle(bundleRoot);
  }

  async save(trace: QueryTrace): Promise<void> {
    try {
      const serialized = JSON.stringify(trace, null, 2);
      if (Buffer.byteLength(serialized) > 64 * 1024) throw new Error("trace exceeds 64 KiB");
      await this.bundle.writeFileAtomic(`${this.dir}/${trace.id}.json`, serialized);
      await this.prune();
    } catch (err) {
      // Tracing is telemetry — never fail the run over it.
      console.error(`[understory] trace save failed: ${(err as Error).message}`);
    }
  }

  async list(): Promise<QueryTrace[]> {
    let files: string[];
    try {
      files = (await this.bundle.listFileNames(this.dir)).filter((f) => f.endsWith(".json"));
    } catch {
      return [];
    }
    const traces: QueryTrace[] = [];
    for (const f of files) {
      try {
        traces.push(JSON.parse(await this.bundle.readFileRaw(`${this.dir}/${f}`)));
      } catch {
        // skip corrupt file
      }
    }
    traces.sort((a, b) => (a.startedAt < b.startedAt ? 1 : -1));
    return traces;
  }

  async read(id: string): Promise<QueryTrace | null> {
    // ids are generated by us; still, never let one escape the traces dir.
    if (!/^[a-z0-9-]+$/.test(id)) return null;
    try {
      return JSON.parse(await this.bundle.readFileRaw(`${this.dir}/${id}.json`));
    } catch {
      return null;
    }
  }

  private async prune(): Promise<void> {
    const files = (await this.bundle.listFileNames(this.dir)).filter((f) => f.endsWith(".json"));
    if (files.length <= MAX_TRACES) return;
    const stats = await Promise.all(
      files.map(async (f) => ({ f, mtime: (await fs.stat(this.bundle.resolve(`${this.dir}/${f}`))).mtimeMs }))
    );
    stats.sort((a, b) => a.mtime - b.mtime);
    for (const { f } of stats.slice(0, stats.length - MAX_TRACES)) {
      await fs.unlink(this.bundle.resolve(`${this.dir}/${f}`)).catch(() => {});
    }
  }
}
